# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 209c5ffda57acbb70d3b889f4d3e0d52f552f2d545166fd6fc34410eb2fddfe33e17a76434e78626a7832e9c8ed42117e997aba73b87463f08754b5039c36c3c

test:
  secret_key_base: f50963c39d0dfe51fb66317e7ce055299888f18f97d2b75baad1ba72195d83f3d6119470fb89dfc47231d0e4cffd8c66e3a825b4c2e23acfd0a93e975c2fa064

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
